#GRIP - TSF | Data Science & Business Analytics Internship
## Task 2 : Exploratory Data Analysis (Retail)

Author : mahmoud mohamed abdelwahab 

Task :
* As a business manager, try to find out the weak areas where you can work to make more profit.
* What all business problems you can derive by exploring the data?
* Dash Boards- explaining the charts and interpretations

####import the useful libraries


In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

upload dataset 

In [3]:
df=pd.read_csv("SampleSuperstore.csv")
df.head(100)

Ship Mode      Segment        Country  ... Quantity Discount    Profit
0     Second Class     Consumer  United States  ...        2     0.00   41.9136
1     Second Class     Consumer  United States  ...        3     0.00  219.5820
2     Second Class    Corporate  United States  ...        2     0.00    6.8714
3   Standard Class     Consumer  United States  ...        5     0.45 -383.0310
4   Standard Class     Consumer  United States  ...        2     0.20    2.5164
..             ...          ...            ...  ...      ...      ...       ...
95  Standard Class  Home Office  United States  ...        1     0.70   -3.7880
96    Second Class  Home Office  United States  ...        7     0.00   40.5426
97     First Class     Consumer  United States  ...        3     0.20   17.9592
98  Standard Class    Corporate  United States  ...        6     0.00   22.5852
99  Standard Class  Home Office  United States  ...        7     0.20   22.6184

[100 rows x 13 columns]

**Data Cleaning** checking dataframe 

1-Missing Values

2-Incorrect Format

3-Incorrect Headers

4-Anomalies/Outliers

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Ship Mode     9994 non-null   object 
 1   Segment       9994 non-null   object 
 2   Country       9994 non-null   object 
 3   City          9994 non-null   object 
 4   State         9994 non-null   object 
 5   Postal Code   9994 non-null   int64  
 6   Region        9994 non-null   object 
 7   Category      9994 non-null   object 
 8   Sub-Category  9994 non-null   object 
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64  
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB


In [6]:
#check missing values
df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

don't exit missing values

In [11]:
#check duplicated rows
bool_series = df.duplicated()
bool_series.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [12]:
# check duplicated values
df[df.duplicated(keep=False)]

Ship Mode      Segment        Country  ... Quantity Discount   Profit
568   Standard Class    Corporate  United States  ...        3      0.0   9.3312
591   Standard Class     Consumer  United States  ...        2      0.2   3.6288
935   Standard Class  Home Office  United States  ...        3      0.2   5.4432
950   Standard Class  Home Office  United States  ...        3      0.2   5.4432
1186  Standard Class    Corporate  United States  ...        4      0.0  12.4416
1479  Standard Class     Consumer  United States  ...        4      0.0  12.4416
2803  Standard Class     Consumer  United States  ...        3      0.0   5.7780
2807    Second Class     Consumer  United States  ...        2      0.0   6.2208
2836  Standard Class     Consumer  United States  ...        3      0.0   9.3312
3127  Standard Class     Consumer  United States  ...        4      0.0  23.0864
3405  Standard Class  Home Office  United States  ...        2      0.3 -12.0588
3406  Standard Class  Home Office  United States  ...        2      0.3 -12.0588
3412  Standard Class    Corporate  United States  ...        4      0.0   3.1752
3670  Standard Class     Consumer  United States  ...        2      0.2   3.6288
4117  Standard Class     Consumer  United States  ...        3      0.0   9.3312
4553  Standard Class     Consumer  United States  ...        3      0.0   5.7780
5372  Standard Class    Corporate  United States  ...        3      0.2   5.4432
5493        Same Day  Home Office  United States  ...        4      0.0  19.8720
5905        Same Day  Home Office  United States  ...        4      0.0  19.8720
6146  Standard Class    Corporate  United States  ...        4      0.0   3.1752
6245  Standard Class  Home Office  United States  ...        3      0.0   6.4206
6334  Standard Class     Consumer  United States  ...        4      0.0  23.0864
6357  Standard Class    Corporate  United States  ...        4      0.0  12.4416
6409     First Class     Consumer  United States  ...        3      0.2  16.1838
7608  Standard Class     Consumer  United States  ...        4      0.0  12.4416
7735  Standard Class    Corporate  United States  ...        3      0.0   9.3312
7759  Standard Class    Corporate  United States  ...        3      0.2   5.4432
8032     First Class     Consumer  United States  ...        3      0.2  16.1838
8095    Second Class     Consumer  United States  ...        2      0.0   6.2208
8457    Second Class    Corporate  United States  ...        3      0.8  -6.2370
8533  Standard Class     Consumer  United States  ...        3      0.0  35.0973
9262  Standard Class     Consumer  United States  ...        3      0.0  35.0973
9363  Standard Class  Home Office  United States  ...        3      0.0   6.4206
9477    Second Class    Corporate  United States  ...        3      0.8  -6.2370

[34 rows x 13 columns]

In [13]:
# drop duplicated values
df.drop_duplicates(inplace=True)

In [14]:
#check second interation 
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Ship Mode, Segment, Country, City, State, Postal Code, Region, Category, Sub-Category, Sales, Quantity, Discount, Profit]
Index: []

**don't exist duplicates vaules in dataframe**


**checking uniques columns in dataframe**




In [22]:
#checking uniques columns in dataframe
df['Ship Mode'].unique()


array(['Second Class', 'Standard Class', 'First Class', 'Same Day'],
      dtype=object)

In [23]:
df['Segment'].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

In [24]:
df['Country'].unique()

array(['United States'], dtype=object)

In [25]:
df['City'].unique()

array(['Henderson', 'Los Angeles', 'Fort Lauderdale', 'Concord',
       'Seattle', 'Fort Worth', 'Madison', 'West Jordan', 'San Francisco',
       'Fremont', 'Philadelphia', 'Orem', 'Houston', 'Richardson',
       'Naperville', 'Melbourne', 'Eagan', 'Westland', 'Dover',
       'New Albany', 'New York City', 'Troy', 'Chicago', 'Gilbert',
       'Springfield', 'Jackson', 'Memphis', 'Decatur', 'Durham',
       'Columbia', 'Rochester', 'Minneapolis', 'Portland', 'Saint Paul',
       'Aurora', 'Charlotte', 'Orland Park', 'Urbandale', 'Columbus',
       'Bristol', 'Wilmington', 'Bloomington', 'Phoenix', 'Roseville',
       'Independence', 'Pasadena', 'Newark', 'Franklin', 'Scottsdale',
       'San Jose', 'Edmond', 'Carlsbad', 'San Antonio', 'Monroe',
       'Fairfield', 'Grand Prairie', 'Redlands', 'Hamilton', 'Westfield',
       'Akron', 'Denver', 'Dallas', 'Whittier', 'Saginaw', 'Medina',
       'Dublin', 'Detroit', 'Tampa', 'Santa Clara', 'Lakeville',
       'San Diego', 'Brentwood', 'Cha

In [26]:
df['State'].unique()

array(['Kentucky', 'California', 'Florida', 'North Carolina',
       'Washington', 'Texas', 'Wisconsin', 'Utah', 'Nebraska',
       'Pennsylvania', 'Illinois', 'Minnesota', 'Michigan', 'Delaware',
       'Indiana', 'New York', 'Arizona', 'Virginia', 'Tennessee',
       'Alabama', 'South Carolina', 'Oregon', 'Colorado', 'Iowa', 'Ohio',
       'Missouri', 'Oklahoma', 'New Mexico', 'Louisiana', 'Connecticut',
       'New Jersey', 'Massachusetts', 'Georgia', 'Nevada', 'Rhode Island',
       'Mississippi', 'Arkansas', 'Montana', 'New Hampshire', 'Maryland',
       'District of Columbia', 'Kansas', 'Vermont', 'Maine',
       'South Dakota', 'Idaho', 'North Dakota', 'Wyoming',
       'West Virginia'], dtype=object)

In [27]:
df['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [28]:
df['Category'].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [33]:
df['Sub-Category'].unique()

array(['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage',
       'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper',
       'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines',
       'Copiers'], dtype=object)

In [30]:
df['Sales'].unique()

array([261.96 , 731.94 ,  14.62 , ..., 437.472,  97.98 , 243.16 ])

In [31]:
df['Discount'].unique()

array([0.  , 0.45, 0.2 , 0.8 , 0.3 , 0.5 , 0.7 , 0.6 , 0.32, 0.1 , 0.4 ,
       0.15])

In [32]:
df['Profit'].unique()

array([ 41.9136, 219.582 ,   6.8714, ...,  16.124 ,   4.1028,  72.948 ])

I note that the country column is the only one that is unique

In [34]:
df.drop(['Country'],axis=1,inplace=True)

In [35]:
df

Ship Mode    Segment             City  ... Quantity  Discount    Profit
0       Second Class   Consumer        Henderson  ...        2      0.00   41.9136
1       Second Class   Consumer        Henderson  ...        3      0.00  219.5820
2       Second Class  Corporate      Los Angeles  ...        2      0.00    6.8714
3     Standard Class   Consumer  Fort Lauderdale  ...        5      0.45 -383.0310
4     Standard Class   Consumer  Fort Lauderdale  ...        2      0.20    2.5164
...              ...        ...              ...  ...      ...       ...       ...
9989    Second Class   Consumer            Miami  ...        3      0.20    4.1028
9990  Standard Class   Consumer       Costa Mesa  ...        2      0.00   15.6332
9991  Standard Class   Consumer       Costa Mesa  ...        2      0.20   19.3932
9992  Standard Class   Consumer       Costa Mesa  ...        4      0.00   13.3200
9993    Second Class   Consumer      Westminster  ...        2      0.00   72.9480

[9977 rows x 12 columns]

 drop useless features like  postal code

In [38]:
df.drop(["Postal Code"],axis=1,inplace=True)

In [39]:
df

Ship Mode    Segment             City  ... Quantity Discount    Profit
0       Second Class   Consumer        Henderson  ...        2     0.00   41.9136
1       Second Class   Consumer        Henderson  ...        3     0.00  219.5820
2       Second Class  Corporate      Los Angeles  ...        2     0.00    6.8714
3     Standard Class   Consumer  Fort Lauderdale  ...        5     0.45 -383.0310
4     Standard Class   Consumer  Fort Lauderdale  ...        2     0.20    2.5164
...              ...        ...              ...  ...      ...      ...       ...
9989    Second Class   Consumer            Miami  ...        3     0.20    4.1028
9990  Standard Class   Consumer       Costa Mesa  ...        2     0.00   15.6332
9991  Standard Class   Consumer       Costa Mesa  ...        2     0.20   19.3932
9992  Standard Class   Consumer       Costa Mesa  ...        4     0.00   13.3200
9993    Second Class   Consumer      Westminster  ...        2     0.00   72.9480

[9977 rows x 11 columns]

**finished data cleaning for dataframe**

# **Exploratory Data Analysis**